# Generated by Django 2.2.8 on 2020-11-07 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0008_material_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Operaciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleOperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.Material')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.Operacion')),
            ],
            options={
                'verbose_name_plural': 'Detalles Operaciones',
            },
        ),
    ]
