# Generated by Django 2.2.8 on 2020-12-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_auto_20200820_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleoperacion',
            old_name='mercaderia',
            new_name='material',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='detalleoperacion',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
