# Generated by Django 2.2.8 on 2020-12-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_remove_detalleoperacion_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleoperacion',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
