# Generated by Django 2.2 on 2021-02-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_detalleoperacion_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleoperacion',
            old_name='precio',
            new_name='precio_unitario',
        ),
        migrations.AddField(
            model_name='detalleoperacion',
            name='precio_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
