# Generated by Django 2.2.8 on 2020-06-28 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0003_auto_20200621_0008'),
        ('complementos_generales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.Material')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complementos_generales.Unidad')),
            ],
            options={
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
