# Generated by Django 2.2.8 on 2021-01-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0009_auto_20201225_2013'),
        ('complementos_generales', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('material', 'unidad')},
        ),
    ]
