# Generated by Django 2.2.8 on 2020-06-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='codigo_barra',
            field=models.ImageField(blank=True, upload_to='materiales'),
        ),
    ]
