# Generated by Django 2.2.8 on 2020-06-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_auto_20200620_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='codigo_barra_imagen',
            field=models.ImageField(blank=True, upload_to='materiales'),
        ),
        migrations.AlterField(
            model_name='material',
            name='codigo_barra',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
