# Generated by Django 2.2.8 on 2020-06-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_auto_20200628_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
