# Generated by Django 2.2.8 on 2020-06-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0005_auto_20200628_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacomercial',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
