# Generated by Django 2.2.8 on 2020-08-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0007_auto_20200628_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
