# Generated by Django 2.2.8 on 2020-12-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0008_material_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='codigo_barra_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='materiales'),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='material',
            name='marca_comercial',
        ),
        migrations.DeleteModel(
            name='MarcaComercial',
        ),
    ]
