# Generated by Django 2.2 on 2021-02-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0009_auto_20201225_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
